-- Additional nationality data for the go-job application
-- This script adds more comprehensive nationality options

INSERT INTO nationality (nationality_name) 
VALUES 
  ('Afghan'),
  ('Albanian'),
  ('Algerian'),
  ('Andorran'),
  ('Angolan'),
  ('Argentine'),
  ('Armenian'),
  ('Australian'),
  ('Austrian'),
  ('Azerbaijani'),
  ('Bahraini'),
  ('Bangladeshi'),
  ('Barbadian'),
  ('Belarusian'),
  ('Belgian'),
  ('Belizean'),
  ('Beninese'),
  ('Bhutanese'),
  ('Bolivian'),
  ('Bosnian'),
  ('Brazilian'),
  ('Bruneian'),
  ('Bulgarian'),
  ('Burkinabe'),
  ('Burmese'),
  ('Burundian'),
  ('Cambodian'),
  ('Cameroonian'),
  ('Canadian'),
  ('Cape Verdean'),
  ('Central African'),
  ('Chadian'),
  ('Chilean'),
  ('Colombian'),
  ('Comoran'),
  ('Congolese'),
  ('Costa Rican'),
  ('Croatian'),
  ('Cuban'),
  ('Cypriot'),
  ('Czech'),
  ('Danish'),
  ('Djiboutian'),
  ('Dominican'),
  ('Dutch'),
  ('Ecuadorian'),
  ('Egyptian'),
  ('Emirati'),
  ('Equatorial Guinean'),
  ('Eritrean'),
  ('Estonian'),
  ('Ethiopian'),
  ('Fijian'),
  ('Finnish'),
  ('French'),
  ('Gabonese'),
  ('Gambian'),
  ('Georgian'),
  ('German'),
  ('Ghanaian'),
  ('Greek'),
  ('Grenadian'),
  ('Guatemalan'),
  ('Guinean'),
  ('Guinea-Bissauan'),
  ('Guyanese'),
  ('Haitian'),
  ('Honduran'),
  ('Hungarian'),
  ('Icelandic'),
  ('Indian'),
  ('Indonesian'),
  ('Iranian'),
  ('Iraqi'),
  ('Irish'),
  ('Israeli'),
  ('Italian'),
  ('Ivorian'),
  ('Jamaican'),
  ('Jordanian'),
  ('Kazakhstani'),
  ('Kenyan'),
  ('Kiribati'),
  ('Kuwaiti'),
  ('Kyrgyz'),
  ('Laotian'),
  ('Latvian'),
  ('Lebanese'),
  ('Lesotho'),
  ('Liberian'),
  ('Libyan'),
  ('Liechtensteiner'),
  ('Lithuanian'),
  ('Luxembourgish'),
  ('Macedonian'),
  ('Malagasy'),
  ('Malawian'),
  ('Malaysian'),
  ('Maldivian'),
  ('Malian'),
  ('Maltese'),
  ('Marshallese'),
  ('Mauritanian'),
  ('Mauritian'),
  ('Mexican'),
  ('Micronesian'),
  ('Moldovan'),
  ('Monacan'),
  ('Mongolian'),
  ('Montenegrin'),
  ('Moroccan'),
  ('Mozambican'),
  ('Namibian'),
  ('Nauruan'),
  ('Nepalese'),
  ('New Zealander'),
  ('Nicaraguan'),
  ('Nigerian'),
  ('Nigerien'),
  ('North Korean'),
  ('Norwegian'),
  ('Omani'),
  ('Pakistani'),
  ('Palauan'),
  ('Palestinian'),
  ('Panamanian'),
  ('Papua New Guinean'),
  ('Paraguayan'),
  ('Peruvian'),
  ('Polish'),
  ('Portuguese'),
  ('Qatari'),
  ('Romanian'),
  ('Russian'),
  ('Rwandan'),
  ('Saint Lucian'),
  ('Salvadoran'),
  ('Samoan'),
  ('San Marinese'),
  ('Sao Tomean'),
  ('Saudi'),
  ('Senegalese'),
  ('Serbian'),
  ('Seychellois'),
  ('Sierra Leonean'),
  ('Singaporean'),
  ('Slovak'),
  ('Slovenian'),
  ('Solomon Islander'),
  ('Somali'),
  ('South African'),
  ('South Korean'),
  ('South Sudanese'),
  ('Spanish'),
  ('Sri Lankan'),
  ('Sudanese'),
  ('Surinamese'),
  ('Swazi'),
  ('Swedish'),
  ('Swiss'),
  ('Syrian'),
  ('Taiwanese'),
  ('Tajik'),
  ('Tanzanian'),
  ('Thai'),
  ('Timorese'),
  ('Togolese'),
  ('Tongan'),
  ('Trinidadian'),
  ('Tunisian'),
  ('Turkish'),
  ('Turkmen'),
  ('Tuvaluan'),
  ('Ugandan'),
  ('Ukrainian'),
  ('Uruguayan'),
  ('Uzbek'),
  ('Vanuatuan'),
  ('Venezuelan'),
  ('Vietnamese'),
  ('Yemeni'),
  ('Zambian'),
  ('Zimbabwean')
ON CONFLICT (nationality_name) DO NOTHING;
